### ISSUE TITLE
Request for the functionality of the checkPermission function

### ISSUE THREAD

**Issue by shinexoh** [santhosh-D-subramani/Shizuku-Plugin#1]
Thank you for your package, your packages have been very helpful to my App.
But I have a feature request:
When calling the `checkPermission` function, it should return a boolean value indicating whether `Shizuku` has authorized the application, rather than popping up a dialog for the user to agree to `Shizuku` permissions before returning this operation's boolean value. I think it might be better to have a separate function call for requesting permissions for `Shizuku`.

Because sometimes I just want to use the `checkPermission` function to check whether `Shizuku` has been authorized, but calling it when not authorized will pop up a dialog, which is a bit inflexible, thank you.

**Comment by shinexoh** [comment]
@santhosh-D-subramani  :))

**Comment by santhosh-D-subramani** [comment]
yeah that makes sense , will work it !

**Comment by santhosh-D-subramani** [comment]
new version released with the feature
